// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 14.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ranta.Gaea.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class NuspecTemplate : NuspecTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 6 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"

    if (this.Solution != null)
    {

            
            #line default
            #line hidden
            this.Write("<?xml version=\"1.0\"?>\r\n<package >\r\n  <metadata>\r\n    <id>");
            
            #line 13 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Solution.FullName));
            
            #line default
            #line hidden
            this.Write("</id>\r\n    <version>1.0.0.0</version>\r\n    <title>");
            
            #line 15 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Solution.FullName));
            
            #line default
            #line hidden
            this.Write(@"</title>
    <authors>Harris Zhang</authors>
    <owners>Harris Zhang</owners>
    <licenseUrl>http://LICENSE_URL_HERE_OR_DELETE_THIS_LINE</licenseUrl>
    <projectUrl>http://PROJECT_URL_HERE_OR_DELETE_THIS_LINE</projectUrl>
    <iconUrl>http://ICON_URL_HERE_OR_DELETE_THIS_LINE</iconUrl>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <description>");
            
            #line 22 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Solution.FullName));
            
            #line default
            #line hidden
            this.Write("</description>\r\n    <releaseNotes>");
            
            #line 23 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Solution.FullName));
            
            #line default
            #line hidden
            this.Write("</releaseNotes>\r\n    <copyright>Copyright ranta 2016</copyright>\r\n    <tags>");
            
            #line 25 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Solution.FullName.Replace(".", " ")));
            
            #line default
            #line hidden
            this.Write(@"</tags>
    <dependencies>
      <dependency id="""" version="""" />
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="""" targetFramework="""" />
    </frameworkAssemblies>
  </metadata>
  <files>
    <file src=""web.config.transform"" target=""content"" />
    <file src=""app.config.transform"" target=""content"" />
");
            
            #line 36 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"

    if (this.Solution.ProjectList != null && this.Solution.ProjectList.Count > 0)
    {
        foreach (var project in this.Solution.ProjectList.Where(v => v.Compile))
        {
            switch (project.ProjectType)
            {
                case Model.ProjectType.Net40:

            
            #line default
            #line hidden
            this.Write("    <file src=\"");
            
            #line 45 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.FullName));
            
            #line default
            #line hidden
            this.Write("\\bin\\Release\\");
            
            #line 45 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.Name));
            
            #line default
            #line hidden
            this.Write(".dll\" target=\"lib\\net40\" />\r\n    <file src=\"");
            
            #line 46 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.FullName));
            
            #line default
            #line hidden
            this.Write("\\bin\\Release\\");
            
            #line 46 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.Name));
            
            #line default
            #line hidden
            this.Write(".xml\" target=\"lib\\net40\" />\r\n");
            
            #line 47 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"

                    break;
                case Model.ProjectType.Net45:

            
            #line default
            #line hidden
            this.Write("    <file src=\"");
            
            #line 51 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.FullName));
            
            #line default
            #line hidden
            this.Write("\\bin\\Release\\");
            
            #line 51 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.Name));
            
            #line default
            #line hidden
            this.Write(".dll\" target=\"lib\\net45\" />\r\n    <file src=\"");
            
            #line 52 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.FullName));
            
            #line default
            #line hidden
            this.Write("\\bin\\Release\\");
            
            #line 52 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.Name));
            
            #line default
            #line hidden
            this.Write(".xml\" target=\"lib\\net45\" />\r\n");
            
            #line 53 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"

                    break;
                case Model.ProjectType.Test:
                default:
                    break;
            }
        }
    }

            
            #line default
            #line hidden
            this.Write("  </files>\r\n</package>\r\n");
            
            #line 64 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\NuspecTemplate.tt"

    }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class NuspecTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
