// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 14.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Ranta.Gaea.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class SolutionTemplate : SolutionTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 6 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"

    if (this.Solution != null)
    {

            
            #line default
            #line hidden
            this.Write("\r\nMicrosoft Visual Studio Solution File, Format Version 12.00\r\n# Visual Studio 14" +
                    "\r\nVisualStudioVersion = 14.0.24720.0\r\nMinimumVisualStudioVersion = 10.0.40219.1\r" +
                    "\n");
            
            #line 15 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"

        switch (this.Solution.ProjectType)
        {
            case 1:
                {

            
            #line default
            #line hidden
            this.Write("Project(\"{2150E333-8FDC-42A3-9474-1A3956D46DE8}\") = \"Solution Items\", \"Solution I" +
                    "tems\", \"");
            
            #line 21 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Guid.NewGuid().ToString("B").ToUpper()));
            
            #line default
            #line hidden
            this.Write("\"\r\n\tProjectSection(SolutionItems) = preProject\r\n\t\t");
            
            #line 23 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Solution.FullName));
            
            #line default
            #line hidden
            this.Write(".bat = ");
            
            #line 23 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Solution.FullName));
            
            #line default
            #line hidden
            this.Write(".bat\r\n\t\t");
            
            #line 24 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Solution.FullName));
            
            #line default
            #line hidden
            this.Write(".nuspec = ");
            
            #line 24 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Solution.FullName));
            
            #line default
            #line hidden
            this.Write(".nuspec\r\n\t\tRantaKey.pfx = RantaKey.pfx\r\n\t\tapp.config.transform = app.config.trans" +
                    "form\r\n\t\tweb.config.transform = web.config.transform\r\n\tEndProjectSection\r\nEndProj" +
                    "ect\r\n");
            
            #line 30 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"

                }
                break;
            default:
                break;
        }

            
            #line default
            #line hidden
            
            #line 37 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"

        if (this.Solution.ProjectList != null && this.Solution.ProjectList.Count > 0)
        {
            foreach (var project in this.Solution.ProjectList)
            {

            
            #line default
            #line hidden
            this.Write("Project(\"");
            
            #line 43 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Solution.Guid.ToString("B").ToUpper()));
            
            #line default
            #line hidden
            this.Write("\") = \"");
            
            #line 43 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.FullName));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 43 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.FullName));
            
            #line default
            #line hidden
            this.Write("\\");
            
            #line 43 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.FullName));
            
            #line default
            #line hidden
            this.Write(".csproj\", \"");
            
            #line 43 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.Guid.ToString("B").ToUpper()));
            
            #line default
            #line hidden
            this.Write("\"\r\nEndProject\r\n");
            
            #line 45 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"

            }
        }

            
            #line default
            #line hidden
            this.Write("Global\r\n\tGlobalSection(SolutionConfigurationPlatforms) = preSolution\r\n\t\tDebug|Any" +
                    " CPU = Debug|Any CPU\r\n\t\tRelease|Any CPU = Release|Any CPU\r\n\tEndGlobalSection\r\n");
            
            #line 54 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"

        if (this.Solution.ProjectList != null && this.Solution.ProjectList.Count > 0)
        {

            
            #line default
            #line hidden
            this.Write("GlobalSection(ProjectConfigurationPlatforms) = postSolution\r\n");
            
            #line 59 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"

            foreach (var project in this.Solution.ProjectList)
            {

            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 63 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.Guid.ToString("B").ToUpper()));
            
            #line default
            #line hidden
            this.Write(".Debug|Any CPU.ActiveCfg = Debug|Any CPU\r\n\t\t");
            
            #line 64 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.Guid.ToString("B").ToUpper()));
            
            #line default
            #line hidden
            this.Write(".Debug|Any CPU.Build.0 = Debug|Any CPU\r\n\t\t");
            
            #line 65 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.Guid.ToString("B").ToUpper()));
            
            #line default
            #line hidden
            this.Write(".Release|Any CPU.ActiveCfg = Release|Any CPU\r\n\t\t");
            
            #line 66 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(project.Guid.ToString("B").ToUpper()));
            
            #line default
            #line hidden
            this.Write(".Release|Any CPU.Build.0 = Release|Any CPU\r\n");
            
            #line 67 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"

            }

            
            #line default
            #line hidden
            this.Write("\tEndGlobalSection\r\n");
            
            #line 71 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write("\tGlobalSection(SolutionProperties) = preSolution\r\n\t\tHideSolutionNode = FALSE\r\n\tEn" +
                    "dGlobalSection\r\n\tEndGlobalSection\r\nEndGlobal\r\n");
            
            #line 79 "D:\BlueWindWorkspace\Ranta\MainLine\Application\Gaea\Ranta.Gaea\Template\SolutionTemplate.tt"

    }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class SolutionTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
