//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ranta.Gaea {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GaeaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GaeaResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ranta.Gaea.GaeaResource", typeof(GaeaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] app_config {
            get {
                object obj = ResourceManager.GetObject("app_config", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;packages&gt;
        ///  &lt;package id=&quot;Microsoft.AspNet.Mvc&quot; version=&quot;5.2.3&quot; targetFramework=&quot;net45&quot; /&gt;
        ///  &lt;package id=&quot;Microsoft.AspNet.Razor&quot; version=&quot;3.2.3&quot; targetFramework=&quot;net45&quot; /&gt;
        ///  &lt;package id=&quot;Microsoft.AspNet.WebPages&quot; version=&quot;3.2.3&quot; targetFramework=&quot;net45&quot; /&gt;
        ///  &lt;package id=&quot;Microsoft.Web.Infrastructure&quot; version=&quot;1.0.0.0&quot; targetFramework=&quot;net45&quot; /&gt;
        ///&lt;/packages&gt; 的本地化字符串。
        /// </summary>
        internal static string mvc_packages {
            get {
                return ResourceManager.GetString("mvc_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;configuration&gt;
        ///  &lt;configSections&gt;
        ///    &lt;sectionGroup name=&quot;system.web.webPages.razor&quot; type=&quot;System.Web.WebPages.Razor.Configuration.RazorWebSectionGroup, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35&quot;&gt;
        ///      &lt;section name=&quot;host&quot; type=&quot;System.Web.WebPages.Razor.Configuration.HostSection, System.Web.WebPages.Razor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35&quot; requirePermission=&quot;false&quot; /&gt;
        ///      &lt;s [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string mvc_view_web_config {
            get {
                return ResourceManager.GetString("mvc_view_web_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] mvc_views_home_index {
            get {
                object obj = ResourceManager.GetObject("mvc_views_home_index", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] mvc_views_shared_layout {
            get {
                object obj = ResourceManager.GetObject("mvc_views_shared_layout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] mvc_views_viewstart {
            get {
                object obj = ResourceManager.GetObject("mvc_views_viewstart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--
        ///  有关如何配置 ASP.NET 应用程序的详细信息，请访问
        ///  http://go.microsoft.com/fwlink/?LinkId=169433
        ///  --&gt;
        ///
        ///&lt;configuration&gt;
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;webpages:Version&quot; value=&quot;3.0.0.0&quot;/&gt;
        ///    &lt;add key=&quot;webpages:Enabled&quot; value=&quot;false&quot;/&gt;
        ///    &lt;add key=&quot;PreserveLoginUrl&quot; value=&quot;true&quot;/&gt;
        ///    &lt;add key=&quot;ClientValidationEnabled&quot; value=&quot;true&quot;/&gt;
        ///    &lt;add key=&quot;UnobtrusiveJavaScriptEnabled&quot; value=&quot;true&quot;/&gt;
        ///  &lt;/appSettings&gt;
        ///
        ///  &lt;system.web&gt;
        ///    
        ///    &lt;httpRuntime targetFramework=&quot;4.5 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string mvc_web_config {
            get {
                return ResourceManager.GetString("mvc_web_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;!-- 有关使用 web.config 转换的详细信息，请访问 http://go.microsoft.com/fwlink/?LinkId=125889 --&gt;
        ///
        ///&lt;configuration xmlns:xdt=&quot;http://schemas.microsoft.com/XML-Document-Transform&quot;&gt;
        ///  &lt;!--
        ///    在下例中，“SetAttributes”转换将更改 
        ///    “connectionString”的值，仅在“Match”定位器 
        ///    查找到值为“MyDB”的特性“name”时使用“ReleaseSQLServer”。
        ///    
        ///    &lt;connectionStrings&gt;
        ///      &lt;add name=&quot;MyDB&quot; 
        ///        connectionString=&quot;Data Source=ReleaseSQLServer;Initial Catalog=MyReleaseDB;Integrated Security=True&quot; 
        ///         [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string mvc_web_debug_config {
            get {
                return ResourceManager.GetString("mvc_web_debug_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///
        ///&lt;!-- 有关使用 web.config 转换的详细信息，请访问 http://go.microsoft.com/fwlink/?LinkId=125889 --&gt;
        ///
        ///&lt;configuration xmlns:xdt=&quot;http://schemas.microsoft.com/XML-Document-Transform&quot;&gt;
        ///  &lt;!--
        ///    在下例中，“SetAttributes”转换将更改 
        ///    “connectionString”的值，仅在“Match”定位器 
        ///    查找到值为“MyDB”的特性“name”时使用“ReleaseSQLServer”。
        ///    
        ///    &lt;connectionStrings&gt;
        ///      &lt;add name=&quot;MyDB&quot; 
        ///        connectionString=&quot;Data Source=ReleaseSQLServer;Initial Catalog=MyReleaseDB;Integrated Security=True&quot; 
        ///         [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string mvc_web_release_config {
            get {
                return ResourceManager.GetString("mvc_web_release_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] web_config {
            get {
                object obj = ResourceManager.GetObject("web_config", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
